executable           = run_make_trees_PUPPI_RUN3_test.sh 
output               = std_make_trees_puppi_2022_$(ProcId)
error                = std_make_trees_puppi_2022_$(ProcId)
log                  = log_make_trees_puppi_2022_$(ProcId)
use_x509userproxy    = True
GetEnv               = True
Universe             = vanilla

transfer_input_files = make_training_trees_PUPPI_RUN3_test.py

arguments            = 130X 2022 puppi $(input) 10 100 $(output_index)
+JobFlavour          = "tomorrow"
MaxTransferOutputMB = -1


input=input_RUN3_2022_0.txt
output_index=test_0
queue

input=input_RUN3_2022_1.txt
output_index=test_1
queue

input=input_RUN3_2022_2.txt
output_index=test_2
queue

input=input_RUN3_2022_3.txt
output_index=test_3
queue

input=input_RUN3_2022_4.txt
output_index=test_4
queue

input=input_RUN3_2022_5.txt
output_index=test_5
queue

input=input_RUN3_2022_6.txt
output_index=test_6
queue

input=input_RUN3_2022_7.txt
output_index=test_7
queue

input=input_RUN3_2022_8.txt
output_index=test_8
queue

input=input_RUN3_2022_9.txt
output_index=test_9
queue

input=input_RUN3_2022_10.txt
output_index=test_10
queue

input=input_RUN3_2022_11.txt
output_index=test_11
queue

input=input_RUN3_2022_12.txt
output_index=test_12
queue

input=input_RUN3_2022_13.txt
output_index=test_13
queue

input=input_RUN3_2022_14.txt
output_index=test_14
queue

input=input_RUN3_2022_15.txt
output_index=test_15
queue

input=input_RUN3_2022_16.txt
output_index=test_16
queue

input=input_RUN3_2022_17.txt
output_index=test_17
queue

input=input_RUN3_2022_18.txt
output_index=test_18
queue

input=input_RUN3_2022_19.txt
output_index=test_19
queue

input=input_RUN3_2022_20.txt
output_index=test_20
queue

input=input_RUN3_2022_21.txt
output_index=test_21
queue

input=input_RUN3_2022_22.txt
output_index=test_22
queue

input=input_RUN3_2022_23.txt
output_index=test_23
queue

input=input_RUN3_2022_24.txt
output_index=test_24
queue

input=input_RUN3_2022_25.txt
output_index=test_25
queue

input=input_RUN3_2022_26.txt
output_index=test_26
queue

input=input_RUN3_2022_27.txt
output_index=test_27
queue

input=input_RUN3_2022_28.txt
output_index=test_28
queue

input=input_RUN3_2022_29.txt
output_index=test_29
queue

input=input_RUN3_2022_30.txt
output_index=test_30
queue

input=input_RUN3_2022_31.txt
output_index=test_31
queue

input=input_RUN3_2022_32.txt
output_index=test_32
queue

input=input_RUN3_2022_33.txt
output_index=test_33
queue

input=input_RUN3_2022_34.txt
output_index=test_34
queue

input=input_RUN3_2022_35.txt
output_index=test_35
queue

input=input_RUN3_2022_36.txt
output_index=test_36
queue

input=input_RUN3_2022_37.txt
output_index=test_37
queue

input=input_RUN3_2022_38.txt
output_index=test_38
queue

input=input_RUN3_2022_39.txt
output_index=test_39
queue

input=input_RUN3_2022_40.txt
output_index=test_40
queue

input=input_RUN3_2022_41.txt
output_index=test_41
queue

input=input_RUN3_2022_42.txt
output_index=test_42
queue

input=input_RUN3_2022_43.txt
output_index=test_43
queue

input=input_RUN3_2022_44.txt
output_index=test_44
queue

input=input_RUN3_2022_45.txt
output_index=test_45
queue

input=input_RUN3_2022_46.txt
output_index=test_46
queue

input=input_RUN3_2022_47.txt
output_index=test_47
queue

input=input_RUN3_2022_48.txt
output_index=test_48
queue

input=input_RUN3_2022_49.txt
output_index=test_49
queue

input=input_RUN3_2022_50.txt
output_index=test_50
queue

input=input_RUN3_2022_51.txt
output_index=test_51
queue

input=input_RUN3_2022_52.txt
output_index=test_52
queue

input=input_RUN3_2022_53.txt
output_index=test_53
queue

input=input_RUN3_2022_54.txt
output_index=test_54
queue

input=input_RUN3_2022_55.txt
output_index=test_55
queue

input=input_RUN3_2022_56.txt
output_index=test_56
queue

input=input_RUN3_2022_57.txt
output_index=test_57
queue

input=input_RUN3_2022_58.txt
output_index=test_58
queue

input=input_RUN3_2022_59.txt
output_index=test_59
queue

input=input_RUN3_2022_60.txt
output_index=test_60
queue

input=input_RUN3_2022_61.txt
output_index=test_61
queue

input=input_RUN3_2022_62.txt
output_index=test_62
queue

input=input_RUN3_2022_63.txt
output_index=test_63
queue

input=input_RUN3_2022_64.txt
output_index=test_64
queue
