executable           = run_make_trees_PUPPI_RUN3.sh 
output               = std_make_trees_puppi_2022_$(ProcId)
error                = std_make_trees_puppi_2022_$(ProcId)
log                  = log_make_trees_puppi_2022_$(ProcId)
use_x509userproxy    = True
GetEnv               = True
Universe             = vanilla

transfer_input_files = make_training_trees_PUPPI_RUN3.py

arguments            = 130X 2022 puppi $(input) 10 100 $(output_index)
+JobFlavour          = "tomorrow"
MaxTransferOutputMB = -1


input=input_RUN3_2022_25.txt
output_index=25
queue
